2021-07-29 11:16:57,025 - root - DEBUG - Initializing Class
2021-07-29 11:17:59,126 - root - DEBUG - Initializing Class
2021-07-29 11:17:59,128 - root - DEBUG - Initializing get_data() function
2021-07-29 11:17:59,488 - git.cmd - DEBUG - Popen(['git', 'version'], cwd=C:\Users\blais\Desktop\10-Academy\week 3\Pharmtec_Sales\notebooks, universal_newlines=False, shell=None, istream=None)
2021-07-29 11:17:59,581 - git.cmd - DEBUG - Popen(['git', 'version'], cwd=C:\Users\blais\Desktop\10-Academy\week 3\Pharmtec_Sales\notebooks, universal_newlines=False, shell=None, istream=None)
2021-07-29 11:17:59,692 - git.util - DEBUG - Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
2021-07-29 11:17:59,885 - git.cmd - DEBUG - Popen(['git', 'version'], cwd=C:\Users\blais\Desktop\10-Academy\week 3\Pharmtec_Sales\notebooks, universal_newlines=False, shell=None, istream=None)
2021-07-29 11:18:00,000 - git.cmd - DEBUG - Popen(['git', 'clone', '-v', '--no-single-branch', '--branch=maindata-v1', '--depth=1', '--progress', 'https://github.com/Blvisse/Pharmtec_Sales', 'C:\\Users\\blais\\AppData\\Local\\Temp\\tmpmoot7vlsdvc-clone'], cwd=C:\Users\blais\Desktop\10-Academy\week 3\Pharmtec_Sales\notebooks, universal_newlines=True, shell=None, istream=None)
2021-07-29 11:18:14,339 - root - DEBUG - Logging parameters to mlflow
2021-07-29 11:18:14,466 - root - DEBUG - Suuccesfully ran function.
2021-07-29 11:18:14,467 - root - INFO - Data URL ----- ..\..\..\..\..\..\..\tmp\dvc-storage\47\3915af4548fa416cc0731e9f3e8ba8 ----- Data Verion ------ maindata-v1 ----- Data rows ------1017209 ------ Data columns ----- 25 --- 

2021-07-29 11:22:03,481 - parso.cache - DEBUG - pickle loaded: C:\ProgramData\Anaconda3\lib\site-packages\jedi\third_party\typeshed\stdlib\2and3\builtins.pyi
2021-07-29 11:22:03,590 - parso.cache - DEBUG - pickle loaded: C:\ProgramData\Anaconda3\lib\site-packages\jedi\third_party\typeshed\stdlib\3\sys.pyi
2021-07-29 11:22:15,702 - parso.python.diff - DEBUG - diff parser start
2021-07-29 11:22:15,707 - parso.python.diff - DEBUG - line_lengths old: 1; new: 2
2021-07-29 11:22:15,708 - parso.python.diff - DEBUG - -> code[replace] old[1:1] new[1:2]
2021-07-29 11:22:15,712 - parso.python.diff - DEBUG - parse_part from 1 to 2 (to 1 in part parser)
2021-07-29 11:22:15,713 - parso.python.diff - DEBUG - diff parser end
2021-07-29 11:26:57,829 - root - DEBUG - Initializing Class
2021-07-29 11:26:58,723 - root - DEBUG - Accessed Clean Outliers Function
2021-07-29 11:27:16,646 - root - INFO - An error occured
2021-07-29 11:27:16,670 - root - ERROR - The following error occured <class 'ValueError'> 
2021-07-29 11:28:24,700 - root - DEBUG - Initializing Class
2021-07-29 11:28:24,890 - root - DEBUG - Accessed Clean Outliers Function
2021-07-29 11:28:37,131 - root - INFO - An error occured
2021-07-29 11:28:37,132 - root - ERROR - The following error occured <class 'ValueError'> 
2021-07-29 11:28:38,153 - root - DEBUG - Initializing Class
2021-07-29 11:29:11,797 - root - DEBUG - Initializing Class
2021-07-29 11:29:11,950 - root - DEBUG - Accessed Clean Outliers Function
2021-07-29 11:29:59,740 - root - INFO - An error occured
2021-07-29 11:29:59,755 - root - ERROR - The following error occured <class 'ValueError'> 
2021-07-29 11:31:32,272 - root - DEBUG - Initializing Class
2021-07-29 11:31:32,742 - root - DEBUG - Accessed Clean Outliers Function
2021-07-29 11:32:23,421 - root - INFO - An error occured
2021-07-29 11:32:23,432 - root - ERROR - The following error occured <class 'ValueError'> 
2021-07-29 11:36:00,936 - parso.python.diff - DEBUG - diff parser start
2021-07-29 11:36:00,942 - parso.python.diff - DEBUG - line_lengths old: 2; new: 3
2021-07-29 11:36:00,942 - parso.python.diff - DEBUG - -> code[replace] old[1:2] new[1:3]
2021-07-29 11:36:00,958 - parso.python.diff - DEBUG - parse_part from 1 to 3 (to 2 in part parser)
2021-07-29 11:36:00,958 - parso.python.diff - DEBUG - diff parser end
2021-07-29 11:36:03,161 - parso.python.diff - DEBUG - diff parser start
2021-07-29 11:36:03,161 - parso.python.diff - DEBUG - line_lengths old: 3; new: 3
2021-07-29 11:36:03,162 - parso.python.diff - DEBUG - -> code[equal] old[1:2] new[1:2]
2021-07-29 11:36:03,163 - parso.python.diff - DEBUG - copy old[1:2] new[1:2]
2021-07-29 11:36:03,163 - parso.python.diff - DEBUG - -> code[replace] old[3:3] new[3:3]
2021-07-29 11:36:03,165 - parso.python.diff - DEBUG - parse_part from 3 to 3 (to 2 in part parser)
2021-07-29 11:36:03,166 - parso.python.diff - DEBUG - diff parser end
2021-07-29 11:36:03,491 - parso.python.diff - DEBUG - diff parser start
2021-07-29 11:36:03,491 - parso.python.diff - DEBUG - line_lengths old: 3; new: 3
2021-07-29 11:36:03,492 - parso.python.diff - DEBUG - -> code[equal] old[1:2] new[1:2]
2021-07-29 11:36:03,493 - parso.python.diff - DEBUG - copy old[1:2] new[1:2]
2021-07-29 11:36:03,493 - parso.python.diff - DEBUG - -> code[replace] old[3:3] new[3:3]
2021-07-29 11:36:03,494 - parso.python.diff - DEBUG - parse_part from 3 to 3 (to 2 in part parser)
2021-07-29 11:36:03,495 - parso.python.diff - DEBUG - diff parser end
2021-07-29 11:36:06,258 - parso.python.diff - DEBUG - diff parser start
2021-07-29 11:36:06,258 - parso.python.diff - DEBUG - line_lengths old: 3; new: 3
2021-07-29 11:36:06,259 - parso.python.diff - DEBUG - -> code[equal] old[1:2] new[1:2]
2021-07-29 11:36:06,260 - parso.python.diff - DEBUG - copy old[1:2] new[1:2]
2021-07-29 11:36:06,261 - parso.python.diff - DEBUG - -> code[replace] old[3:3] new[3:3]
2021-07-29 11:36:06,262 - parso.python.diff - DEBUG - parse_part from 3 to 3 (to 2 in part parser)
2021-07-29 11:36:06,262 - parso.python.diff - DEBUG - diff parser end
2021-07-29 11:36:44,643 - root - DEBUG - Initializing Class
2021-07-29 11:36:55,468 - root - DEBUG - Initializing Class
2021-07-29 11:37:04,491 - root - DEBUG - Initializing Class
2021-07-29 11:37:10,980 - root - DEBUG - Initializing Class
2021-07-29 11:37:10,981 - root - DEBUG - -------------------------------- Acessing label Encoding Functoin --------------------------------
2021-07-29 11:37:10,983 - root - DEBUG - encoding columns
2021-07-29 11:37:30,868 - parso.python.diff - DEBUG - diff parser start
2021-07-29 11:37:30,868 - parso.python.diff - DEBUG - line_lengths old: 3; new: 1
2021-07-29 11:37:30,869 - parso.python.diff - DEBUG - -> code[replace] old[1:3] new[1:1]
2021-07-29 11:37:30,869 - parso.python.diff - DEBUG - parse_part from 1 to 1 (to 0 in part parser)
2021-07-29 11:37:30,870 - parso.python.diff - DEBUG - diff parser end
2021-07-29 11:37:36,745 - parso.python.diff - DEBUG - diff parser start
2021-07-29 11:37:36,745 - parso.python.diff - DEBUG - line_lengths old: 1; new: 1
2021-07-29 11:37:36,746 - parso.python.diff - DEBUG - -> code[replace] old[1:1] new[1:1]
2021-07-29 11:37:36,748 - parso.python.diff - DEBUG - parse_part from 1 to 1 (to 0 in part parser)
2021-07-29 11:37:36,749 - parso.python.diff - DEBUG - diff parser end
2021-07-29 11:37:39,329 - parso.python.diff - DEBUG - diff parser start
2021-07-29 11:37:39,329 - parso.python.diff - DEBUG - line_lengths old: 1; new: 1
2021-07-29 11:37:39,330 - parso.python.diff - DEBUG - -> code[replace] old[1:1] new[1:1]
2021-07-29 11:37:39,331 - parso.python.diff - DEBUG - parse_part from 1 to 1 (to 0 in part parser)
2021-07-29 11:37:39,332 - parso.python.diff - DEBUG - diff parser end
2021-07-29 11:37:51,564 - root - DEBUG - ------- Accessing the ordinal function ------------
2021-07-29 11:37:51,567 - root - DEBUG - Initializng OrdinalEncoder
2021-07-29 11:37:51,571 - root - INFO - An error occured
2021-07-29 11:37:51,573 - root - ERROR - The following error has occured: <class 'ValueError'> 
